import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import HorizontalCard from "../components/Cards/HorizontalCard";
import ProfileCard from "../components/Cards/ProfileCard";
import HeroComp from "../components/HeroComp";
import NavBar from "../components/NavBar";
import styles from "../styles/Home.module.css";

const Home: NextPage = (props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
    </div>
  );
};

export default Home;
